name: My First CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say hello
        run: echo "Pipeline is working!"

      - name: Check the environment
        run: |
          echo "Current directory:"
          pwd
          echo "Files in repo:"
          ls
